name: Run flutter tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: holmusk/flutter-ci:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
